version: "3"
services:
    bo_watch:
        image: bigobject/watch:$VERSION
        container_name: bo_watch
        volumes: 
            - $PROJECT_DIR/share/nagios_var:/usr/local/nagios/var
            - $PROJECT_DIR/share/nagios_etc:/usr/local/nagios/etc/custom
        extra_hosts:
            - "hostName:IPAddress"
        ports:
            - "5407:80"
        environment:
            - NAGIOS_PSWD=nagios
            - SLACK_URL=https://hooks.slack.com/services/...
        working_dir: /opt
        stdin_open: true
        tty: true
        command: bash
        restart: unless-stopped